### ISSUE TITLE
"You must target Windows 10 or later in your 'app.manifest' and run without debugging."

### ISSUE THREAD

**Issue by ruhchjdbdbhccjjc** [Grabacr07/VirtualDesktop#73]
Hi,
When I use this library,In some case(console sofware and vsto--- i tried .net4.72 version that pulled in pull requests! ),always get error:"You must target Windows 10 or later in your 'app.manifest' and run without debugging." ,but i created a app.manifest file and target windows 10.
So the library only Can be used in wpf ? otherwise , I am wrong?
Anyone can help me?

**Comment by iskmz** [comment]
found this post while having the  same problem ... and I think it is solved ... 
used .net 4.6 in my console app and VirtualDesktop.dll version 2.0.0.0 (pretty old) 
but the things that made this error / exception go away is  Project->Properties->Application->OutputType->WindowsApplication instead of Console Application 
Also you must do the app.manifest thing as stated in README ...

**Comment by ruhchjdbdbhccjjc** [comment]
@iskmz Thank your help!
